### ISSUE TITLE
Server is full?

### ISSUE THREAD

**Issue by WJKH** [dahquan/rattlesnake#61]
I was testing the example feedme.js and I'm getting fews bots with 200 private proxies, connecting 2 per IP.

I guess the reason is the server is full and rejects the connection, then I'm getting an error and not reconnecting.

> { Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

By the way, this affect the bot counter [Bots Alive: -383]
I have fixed the bot counter changing the following code:

`      bot.on('disconnected', function() {
        alive--
        print(bot.name + ' died')
      })`
`      bot.on('died', function() {
        alive--
        print(bot.name + ' died')
      })`

Now the bot amout is right. but the issue is when the server is full and reject the connetion.

**Comment by anonymousxxx02** [comment]
its ok that i share your code here https://github.com/l3mpik/slither-feeder-bot/issues/29 ???

**Comment by WJKH** [comment]
@anonymousxxx02 it's just one line of code, I don't care about credits.

Anyway it's not going to fix the real issue, it's just a workaround to get an accurate number of alive bots but if proxy fail....

The issue is the server rejects clients because it's fully, the actual code doesn't try to connect more clients when the server get some free slots.
Today I realized that the game devs has implemented a limitation on connections or something like that, because I can't connect more than 100 bots. Can someone connect more than 100 bots right now?

**Comment by anonymousxxx02** [comment]
i play with 120-180 bots and also chither.com is selling max 240 bots

**Comment by WJKH** [comment]
Well, yesterday I could connect upto 300 bots in servers with 200-300 players.
Today I can't connect more than 100, tried different servers and I can't.

Chither and others aren't using this framework and probably find the way to bypass this protection.

**Comment by anonymousxxx02** [comment]
i am playing with 120 -140 bots right now

**Comment by WJKH** [comment]
@anonymousxxx02 weird, I'm using @dahquan files with some modifications but should be the same.
@l3mpik did you made any modification like as interval between connections or something like it?

**Comment by anonymousxxx02** [comment]
@WJKH i am using 800 unchecked socks and tooday i had above 200 bots.

**Comment by WJKH** [comment]
@anonymousxxx02 the last version of @l3mpik repository isn't working.
I will check the version you upload to Mega.

**Comment by anonymousxxx02** [comment]
@WJKH the version in mega have some issue with server i will upload new one soon

**Comment by anonymousxxx02** [comment]
@WJKH  https://www.youtube.com/watch?v=IKh1IM1rdcw

**Comment by WJKH** [comment]
@anonymousxxx02 I tried with your version and it's working right with socks.

Then I have found my issue wasn't any server limitation, it's related to the http proxies I was using.
Basically most proxies doesn't support tunneling.
@dahquan is tunneling really need? can we use some other proxy lib?

**Comment by WJKH** [comment]
By the way, the server is full issue is still there as the current code doesn't try to connect more bots when there're more slots in the server.

**Comment by anonymousxxx02** [comment]
@WJKH the real issue is when you die and change server bots dont reconnect.... i was playing in the same server about an hour with 250 bots all the time but when i change server bots start drop down

**Comment by WJKH** [comment]
@anonymousxxx02 yes, but @dahquan already said it's not supported yet.
You need restart the feeder to get a new server.

I will check later if I can get it done, should be simple to add an if to compare old_server != actual_server then reconnect all bots.

**Comment by anonymousxxx02** [comment]
@WJKH the script of @l3mpik support server change without restart the feeder but i think the problem in @l3mpik script is that when you die and change server some  bots keep spawning in the old server...i m not sure yet but i think this is the problem. When i first start playing the bot count show 200 bots and thay are a lot of bots in the server. when i die and change server the bot count show 300 bots but they are not to mutch bots and c9.io is overload . So i supose that some bots run in the old server

**Comment by WJKH** [comment]
@anonymousxxx02 I couldn't test @l3mpik version yet (not working) but when you change server you need call bot.close before to call bot.connect again.

**Comment by anonymousxxx02** [comment]
I thought this hapend automatic by typing on/off button but let me double check

**Comment by anonymousxxx02** [comment]
@WJKH how to call bot.close and bot.connect ???

**Comment by anonymousxxx02** [comment]
@WJKH in the @l3mpik code the bots run also in the old server... do you know how to fix that ??

**Comment by WJKH** [comment]
@anonymousxxx02 there's not bot.close in your feeder.js then if you want close the connection without killing the process you need call bot.close from bot.js

`  // close
  close() {
    if(this.conn !== null) {
      this.conn.close()
    }
  }`

You already call bot.connect in your feeder.js in the spawn function line 71
`      bot.connect(proxy);`

If you have done change server function just call bot.close before to call spawn function or put the call at the beginning of spawn function then before to connect you will close.
