### ISSUE TITLE
Node.js doesnt start up feedme.js and i see nowhere to log in

### ISSUE THREAD

**Issue by SIrStarch** [dahquan/rattlesnake#83]
> node examples/feedme.js
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:236:25)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
    at REPLServer.Interface._line (readline.js:566:8)
    at REPLServer.Interface._ttyWrite (readline.js:843:14)
>

**Comment by SIrStarch** [comment]
what must i do
