### ISSUE TITLE
Issue with the bots!

### ISSUE THREAD

**Issue by SoloZYT** [dahquan/rattlesnake#88]
| | |   | `-- is-dotfile@1.0.2
| | |   `-- regex-cache@0.4.3
| | |     +-- is-equal-shallow@0.1.3
| | |     `-- is-primitive@2.0.0
| | +-- async-each@1.0.0
| | +-- glob-parent@2.0.0
| | +-- inherits@2.0.1
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.4.1
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| | `-- readdirp@2.0.0
| |   `-- graceful-fs@4.1.4
| +-- commander@2.9.0
| | `-- graceful-readlink@1.0.1
| +-- convert-source-map@1.2.0
| +-- fs-readdir-recursive@0.1.2
| +-- glob@5.0.15
| | +-- inflight@1.0.5
| | | `-- wrappy@1.0.2
| | `-- once@1.3.3
| +-- lodash@4.13.1
| +-- log-symbols@1.0.2
| | `-- chalk@1.1.3
| +-- output-file-sync@1.1.1
| | `-- xtend@4.0.1
| +-- path-exists@1.0.0
| +-- path-is-absolute@1.0.0
| +-- slash@1.0.0
| +-- source-map@0.5.6
| `-- v8flags@2.0.11
|   `-- user-home@1.1.1
+-- babel-plugin-add-module-exports@0.2.1
+-- babel-preset-es2015@6.9.0
| +-- babel-plugin-check-es2015-constants@6.8.0
| +-- babel-plugin-transform-es2015-arrow-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoping@6.9.0
| +-- babel-plugin-transform-es2015-classes@6.9.0
| | +-- babel-helper-define-map@6.9.0
| | +-- babel-helper-function-name@6.8.0
| | +-- babel-helper-optimise-call-expression@6.8.0
| | `-- babel-helper-replace-supers@6.8.0
| +-- babel-plugin-transform-es2015-computed-properties@6.8.0
| +-- babel-plugin-transform-es2015-destructuring@6.9.0
| +-- babel-plugin-transform-es2015-duplicate-keys@6.8.0
| +-- babel-plugin-transform-es2015-for-of@6.8.0
| +-- babel-plugin-transform-es2015-function-name@6.9.0
| +-- babel-plugin-transform-es2015-literals@6.8.0
| +-- babel-plugin-transform-es2015-modules-commonjs@6.8.0
| | `-- babel-plugin-transform-strict-mode@6.8.0
| +-- babel-plugin-transform-es2015-object-super@6.8.0
| +-- babel-plugin-transform-es2015-parameters@6.9.0
| | +-- babel-helper-call-delegate@6.8.0
| | | `-- babel-helper-hoist-variables@6.8.0
| | `-- babel-helper-get-function-arity@6.8.0
| +-- babel-plugin-transform-es2015-shorthand-properties@6.8.0
| +-- babel-plugin-transform-es2015-spread@6.8.0
| +-- babel-plugin-transform-es2015-sticky-regex@6.8.0
| | `-- babel-helper-regex@6.9.0
| +-- babel-plugin-transform-es2015-template-literals@6.8.0
| +-- babel-plugin-transform-es2015-typeof-symbol@6.8.0
| +-- babel-plugin-transform-es2015-unicode-regex@6.8.0
| | `-- regexpu-core@1.0.0
| |   +-- regenerate@1.3.1
| |   +-- regjsgen@0.2.0
| |   `-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
| `-- babel-plugin-transform-regenerator@6.9.0
|   `-- babel-plugin-syntax-async-functions@6.8.0
+-- babel-register@6.9.0
| +-- core-js@2.4.0
| +-- home-or-tmp@1.0.0
| | `-- os-tmpdir@1.0.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| `-- source-map-support@0.2.10
|   `-- source-map@0.1.32
|     `-- amdefine@1.0.0
+-- colors@1.1.2
+-- express@4.13.4
| +-- accepts@1.2.13
| | `-- negotiator@0.5.3
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.1
| +-- content-type@1.0.2
| +-- cookie@0.1.5
| +-- cookie-signature@1.0.6
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- depd@1.1.0
| +-- escape-html@1.0.3
| +-- etag@1.7.0
| +-- finalhandler@0.4.1
| | `-- unpipe@1.0.0
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@1.0.10
| | +-- forwarded@0.1.0
| | `-- ipaddr.js@1.0.5
| +-- qs@4.0.0
| +-- range-parser@1.0.3
| +-- send@0.13.1
| | +-- destroy@1.0.4
| | +-- http-errors@1.3.1
| | +-- mime@1.3.4
| | `-- statuses@1.2.1
| +-- serve-static@1.10.3
| | `-- send@0.13.2
| +-- type-is@1.6.13
| | `-- media-typer@0.3.0
| +-- utils-merge@1.0.0
| `-- vary@1.0.1
+-- http-proxy@1.13.3
| +-- eventemitter3@1.2.0
| `-- requires-port@1.0.0
+-- request@2.72.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.4.1
| +-- bl@1.1.2
| | `-- readable-stream@2.0.6
| |   +-- core-util-is@1.0.2
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   +-- string_decoder@0.10.31
| |   `-- util-deprecate@1.0.2
| +-- caseless@0.11.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.0
| +-- forever-agent@0.6.1
| +-- form-data@1.0.0-rc4
| | `-- async@1.5.2
| +-- har-validator@2.0.6
| | +-- is-my-json-valid@2.13.1
| | | +-- generate-function@2.0.0
| | | +-- generate-object-property@1.2.0
| | | | `-- is-property@1.0.2
| | | `-- jsonpointer@2.0.0
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.2.2
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.2
| | | `-- verror@1.3.6
| | `-- sshpk@1.8.3
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- dashdash@1.14.0
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.6
| |   | `-- assert-plus@1.0.0
| |   +-- jodid25519@1.0.2
| |   +-- jsbn@0.1.0
| |   `-- tweetnacl@0.13.3
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.11
| | `-- mime-db@1.23.0
| +-- node-uuid@1.4.7
| +-- oauth-sign@0.8.2
| +-- qs@6.1.0
| +-- stringstream@0.0.5
| +-- tough-cookie@2.2.2
| `-- tunnel-agent@0.4.3
+-- socks-proxy-agent@2.0.0
| +-- agent-base@2.0.1
| | `-- semver@5.0.3
| `-- socks@1.1.9
|   +-- ip@1.1.3
|   `-- smart-buffer@1.0.11
+-- tunnel@0.0.4
+-- websocket@1.0.23
| +-- nan@2.3.5
| +-- typedarray-to-buffer@3.1.2
| `-- yaeti@0.0.4
`-- winston@2.2.0
  +-- async@1.0.0
  +-- colors@1.0.3
  +-- cycle@1.0.3
  +-- eyes@0.1.8
  +-- pkginfo@0.3.1
  `-- stack-trace@0.0.9

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.12

C:\Users\Lucas\Desktop\rattlesnake-master\examples>node feedme
Feed Me Bot
1. Open a browser and navigate to http://slither.io
2. Open this script file (examples/feedme.js) and copy the browser code all the
way at the top of the file
3. Go to the developer console then paste the browser code and press enter
4. Login normally and you should see your bots start to connect

** Bots will stay on the same server even if you die and will NOT switch servers
, to stop it press Ctrl+C
[Bots Alive: 0]         Spawning 16262 snakes
ReferenceError: bots is not defined
    at C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:138:7
    at Array.forEach (native)
    at spawn (C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:114:1
1)
    at C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:170:5
    at Layer.handle [as handle_request] (C:\Users\Lucas\Desktop\rattlesnake-mast
er\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib\
router\route.js:131:13)
    at Route.dispatch (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\ex
press\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Lucas\Desktop\rattlesnake-mast
er\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib\router
\index.js:277:22
    at param (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib
\router\index.js:349:14)
^C
C:\Users\Lucas\Desktop\rattlesnake-master\examples>node feedme
Feed Me Bot
1. Open a browser and navigate to http://slither.io
2. Open this script file (examples/feedme.js) and copy the browser code all the
way at the top of the file
3. Go to the developer console then paste the browser code and press enter
4. Login normally and you should see your bots start to connect

** Bots will stay on the same server even if you die and will NOT switch servers
, to stop it press Ctrl+C
[Bots Alive: 0]         Spawning 16262 snakes
ReferenceError: bots is not defined
    at C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:138:7
    at Array.forEach (native)
    at spawn (C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:114:1
1)
    at C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme.js:170:5
    at Layer.handle [as handle_request] (C:\Users\Lucas\Desktop\rattlesnake-mast
er\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib\
router\route.js:131:13)
    at Route.dispatch (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\ex
press\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Lucas\Desktop\rattlesnake-mast
er\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib\router
\index.js:277:22
    at param (C:\Users\Lucas\Desktop\rattlesnake-master\node_modules\express\lib
\router\index.js:349:14)
^C
C:\Users\Lucas\Desktop\rattlesnake-master\examples>npm install feedme.js
npm ERR! not a package C:\Users\Lucas\Desktop\rattlesnake-master\examples\feedme
.js
npm ERR! addLocal Could not install C:\Users\Lucas\Desktop\rattlesnake-master\ex
amples\feedme.js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Desktop\\node.exe" "C:\\Desktop\\node_modules\\npm\\bin\\npm-
cli.js" "install" "feedme.js"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path C:\Users\Lucas\AppData\Local\Temp\npm-10464-915b9355\unpack-f43ac4
94\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Lucas\AppData\
Local\Temp\npm-10464-915b9355\unpack-f43ac494\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Lucas\AppData\
Local\Temp\npm-10464-915b9355\unpack-f43ac494\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lucas\Desktop\rattlesnake-master\examples\npm-debug.log

C:\Users\Lucas\Desktop\rattlesnake-master\examples>node feedme
Feed Me Bot
1. Open a browser and navigate to http://slither.io
2. Open this script file (examples/feedme.js) and copy the browser code all the
way at the top of the file
3. Go to the developer console then paste the browser code and press enter
4. Login normally and you should see your bots start to connect

** Bots will stay on the same server even if you die and will NOT switch servers
, to stop it press Ctrl+C

**Comment by ravyn120** [comment]
Try reinstalling node.js

**Comment by mastkilxp** [comment]
and you should lower the proxies. there wont be really 16k snakes server limit is around 580-600 i believe that might be the issue not sure.

**Comment by SrNicolas** [comment]
" bots is not defined" there u go just read the error ...
