### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by mor120** [dahquan/rattlesnake#97]
When I do the command "node examples/leaderboard.js" in Node.js it gives me that error:

> SyntaxError: Unexpected identifier
>     at Object.exports.createScript (vm.js:24:10)
>     at REPLServer.defaultEval (repl.js:236:25)
>     at bound (domain.js:280:14)
>     at REPLServer.runBound [as eval] (domain.js:293:12)
>     at REPLServer.<anonymous> (repl.js:441:10)
>     at emitOne (events.js:101:20)
>     at REPLServer.emit (events.js:188:7)
>     at REPLServer.Interface._onLine (readline.js:224:10)
>     at REPLServer.Interface._line (readline.js:566:8)
>     at REPLServer.Interface._ttyWrite (readline.js:843:14)

Have to say that I never worked with Node.js so maybe i do something wrong.

**Comment by mastkilxp** [comment]
you sure you installed node.js?
and theres no need to do that command what u just did
